### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Dolu1990** [SpinalHDL/SaxonSoc#4]
- [x] SDRAM working in sim
- [x] Linux working in sim
- [x] Figuring out the exact linux memory mapping requirements
- [x] Having a common memory map between non cached and cached stuff
- [x] Defining basic cacheless and  cache-full-linux-ready SoCs
- [x] Having hardware to run those two soc
- [x] Having a ice40 XIP SoC
- [ ] Having Linux on ice40 8K
- [ ] BMB decoder should protect slaves from access with burst length too long
- [x] Soc on UP5K
- [ ] Bmb flow/Stream rsp
- [x] Linux boot loader
- [x] SDRAM-DDR support
